---
- name: Setup Prometheus and Grafana
  hosts: monitoring
  become: yes
  roles:
    - role: grafana.grafana.grafana
      vars:
        grafana_security:
           admin_user: admin
           admin_password: admin

    - role: prometheus.prometheus.prometheus
      vars:
        prometheus_agent_mode: false
        prometheus_config_flags_extra:
          web.enable-remote-write-receiver: ""

