alertmanager:
  enabled: false

grafana:
  enabled: false

prometheus:
  prometheusSpec:
    remoteWrite:
      - url: "http://<Mention Prom Server Private IP>:9090/api/v1/write"
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
