alertmanager:
  enabled: false

grafana:
  enabled: false

prometheus:
  prometheusSpec:
    remoteWrite:
      - url: "http://172.31.33.202:9090/api/v1/write"
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false